language: node_js

node_js:
  - "8"

install:
  - cnpm install

script:
  - cnpm run build

# 分支白名单
branches:
  only:
    - master # 只对 master 分支进行构建

# GitHub Pages 部署
deploy:
  provider: pages
  skip_cleanup: true
  # 令牌秘钥，在主页面用户的 Setting 中创建
  github_token: $GITHUB_TOKEN
  # 将 dist 目录下的内容推送到默认的 gh-pages 分支上
  local_dir: dist
  target_branch: gh-pages
  on:
    branch: master
